site_name: Homerun2 Scout
site_description: Periodic analytics service for RediSearch data

nav:
  - Home: index.md
  - API Usage: api-usage.md
  - Deployment: deployment.md
  - CI/CD: cicd.md

plugins:
  - techdocs-core
