---
name: Cleanup PR Artifacts
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cleanup:
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-cleanup-pr-artifacts.yaml@main
    with:
      runs-on: ubuntu-latest
      packages: homerun2-scout,homerun2-scout-kustomize
      dry-run: false
    secrets: inherit # pragma: allowlist secret
