---
name: Comment Preview URL on PR
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  comment:
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-comment-preview-url.yaml@main
    with:
      hostname-prefix: scout-pr
      hostname-domain: homerun2-dev.sthings-vsphere.labul.sva.de
      namespace-prefix: homerun2-scout-pr
    secrets: inherit # pragma: allowlist secret
